# Generated by Django 4.0.5 on 2022-06-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('idqrcode', models.IntegerField(db_column='idQRcode', primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=45, null=True)),
                ('latitude', models.CharField(blank=True, max_length=45, null=True)),
                ('longitude', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'QRcode',
                'managed': False,
            },
        ),
    ]
