# Generated by Django 4.0.5 on 2022-06-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('seqId', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='email', max_length=45)),
                ('password', models.CharField(db_column='password', max_length=300)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
